// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Routine.Api.Data;

namespace Routine.Api.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    [Migration("20200427102742_AddEmployeeData")]
    partial class AddEmployeeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Routine.Api.Models.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a41019-4697-4048-ba96-ae94f58efec9"),
                            Introduction = "Great Company",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("83124751-6f30-4a49-b712-a255126bed87"),
                            Introduction = "Bad Company",
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("1afca17b-af76-4f79-a011-cea83f852e6a"),
                            Introduction = "Fubao 4 Company",
                            Name = "Alibaba"
                        });
                });

            modelBuilder.Entity("Routine.Api.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a41019-4697-4048-ba96-cea83f852e6a"),
                            CompanyId = new Guid("f6a41019-4697-4048-ba96-ae94f58efec9"),
                            DateOfBirth = new DateTime(1990, 4, 27, 18, 27, 42, 486, DateTimeKind.Local).AddTicks(9002),
                            EmployeeNo = "MSF324",
                            FirstName = "Li",
                            Gender = 2,
                            LastName = "si"
                        },
                        new
                        {
                            Id = new Guid("1afca17b-4697-4048-af76-cea83f852e6a"),
                            CompanyId = new Guid("f6a41019-4697-4048-ba96-ae94f58efec9"),
                            DateOfBirth = new DateTime(2000, 4, 27, 18, 27, 42, 487, DateTimeKind.Local).AddTicks(6030),
                            EmployeeNo = "MSF314",
                            FirstName = "Wang",
                            Gender = 1,
                            LastName = "wu"
                        });
                });

            modelBuilder.Entity("Routine.Api.Models.Entities.Employee", b =>
                {
                    b.HasOne("Routine.Api.Models.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
